version: '3.0'
services:
  rasa:
    environment:
      - UID=1000
      - GID=1001
    user: "${UID}:${GID}"
    image: rasa/rasa:3.0.1-full
    # build:
    #   context: ./rasa
    # container_name: rasa-server
    ports:
      - "5005:5005"
    volumes:  
      - ./rasa:/app
    command:
      - run
      - --cors
      - "*"
      - --enable-api
      - --debug
      - --log-file
      - out.log
    networks:
      - rasa
    depends_on:
      - action-server

  action-server:
    build:
      context: ./action-server
    container_name: rasa-action-server
#    image: rasa/rasa-sdk:3.0.2
    volumes:
      - ./action-server/custom_actions:/app/actions
    ports:
      - "5055:5055"
    networks:
      - rasa

  chatbot:
    build:
      context: ./chatbot
    ports:
      - "5000:5000"
    networks:
      - rasa
  notebook-playground:
    build:
      context: ./notebook-playground
    networks:
      - rasa
    volumes:
      - ./notebook-playground/notebooks:/workspace
    ports:
      # Jupyter Notebook port - always map from 8888 to any available port
      - 8888:8888

networks:
  rasa:
